name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui-android
        dotnet workload restore
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Android target for tests
      run: dotnet build Grocery.App/Grocery.App.csproj --configuration Release -f net8.0-android
      
    - name: Run tests with Android target
      run: dotnet test Grocery.App/Grocery.App.csproj --configuration Release -f net8.0-android --logger "trx;LogFileName=test-results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: "**/*.trx"
        retention-days: 30

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "**/*.trx"
        reporter: dotnet-trx

  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui-android
        dotnet workload restore
        
    - name: Build Android
      run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android
