name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Check directory structure
      run: |
        echo "📁 Directory listing:"
        ls -la
        
    - name: Restore test project dependencies
      run: dotnet restore TestCore/TestCore.csproj
      
    - name: Build test project
      run: dotnet build TestCore/TestCore.csproj --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test TestCore/TestCore.csproj --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: "**/*.trx"
        retention-days: 30

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "**/*.trx"
        reporter: dotnet-trx

  build:
    name: Build MAUI Application
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui-android
        dotnet workload restore
        
    - name: Temporarily modify csproj to exclude iOS on Linux
      run: |
        cd Grocery.App
        # Backup original file
        cp Grocery.App.csproj Grocery.App.csproj.backup
        # Replace TargetFrameworks with single TargetFramework for Android only
        sed -i 's/<TargetFrameworks>.*<\/TargetFrameworks>/<TargetFramework>net8.0-android<\/TargetFramework>/g' Grocery.App.csproj
        echo "Modified csproj content:"
        grep -i target Grocery.App.csproj
        
    - name: Build Android
      run: dotnet build Grocery.App/Grocery.App.csproj -c Release

    - name: Restore original csproj
      if: always()
      run: |
        cd Grocery.App
        cp Grocery.App.csproj.backup Grocery.App.csproj
